#ifndef PN7462AU_VERSION_INFO_H_INCLUDED
#define PN7462AU_VERSION_INFO_H_INCLUDED


/*
 *                  Copyright (c), NXP Semiconductors
 *
 *                     (C)NXP Semiconductors
 *       All rights are reserved. Reproduction in whole or in part is
 *      prohibited without the written consent of the copyright owner.
 *  NXP reserves the right to make changes without notice at any time.
 * NXP makes no warranty, expressed, implied or statutory, including but
 * not limited to any implied warranty of merchantability or fitness for any
 *particular purpose, or that the use will not infringe any third party patent,
 * copyright or trademark. NXP must not be liable for any loss or damage
 *                          arising from its use.
 */
/*
 * Version Information
 * Auto-Generated by:
 *     docs\22_rel_doc\version_update.py (v2016.12.11_00)
 *
 * Do not edit this file. Update version_info.txt instead. */


#define PN7462AU_VER_FILEDESCRIPTION    "PN7462AU_04.11.00_20170822"
#define PN7462AU_VER_FILEVERSION         4,11,0,2
#define PN7462AU_VER_FILEVERSION_STR    "4,11,0,2"
#define PN7462AU_VER_PRODUCTVERSION      4,11,0,2
#define PN7462AU_VER_PRODUCTVERSION_STR "4,11,0,2"
#define PN7462AU_VER_MAJOR  (4)
#define PN7462AU_VER_MINOR  (11)
#define PN7462AU_VER_DEV    (0)

/* ______GENERATED_FROM____version_info.txt
 * # _____________________________________________________________________________
 * # Product Description
 * #
 *
 * sw_c_define_name = "PN7462AU"
 * sw_product_name  = "PN7462AU" # Product Name
 * #sw_cs_namespace  =
 * sw_v_major       = "04"       # Major Release NNX
 * sw_v_minor       = "11"       # SW Minor Version
 * sw_v_dev         = "00"       # SW Development Version
 * sw_maturity      = "B"        # SW Maturity "A" Alpha, "B":Beta, "P": Production
 * sw_metastring    = ""         # Any meta string
 * # _____________________________________________________________________________
 * #
 * # History: Descending
 * #
 * # 04.11.00 : PN7462AU_04.11.00_20170822
 * #          : [artf251456]
 * #
 * # 04.10.00 : PN7462AU_04.10.00_20170412
 * #          : [artf239414] [artf241300 ]
 * #
 * # 04.09.00 : PN7462AU_04.09.00_20161214
 * #		   : [artf206946] [artf214376] [artf191668]
 * #          : [artf178091] [artf171220]
 * #          :
 * # 04.08.00 : PN7462AU_04.08.00_20161205
 * #		   : [artf171220] [artf206946] [artf191668]
 * #          : [artf178091] [artf214376]
 * #		   :
 * # 04.05.00 : PN7462AU_04_05_00_20160929
 * #		   : artf203312, artf203313, artf203314, artf203315
 * #		   :
 * # 04.04.00 : PN7462AU_04_04_00_20160923
 * #		   : artf183395 artf193845 artf193841 artf195805 artf176443 artf193890
 * #
 * # 04.03.02 : PN7462AU_04_03_02_20160809 / EE=r27.0.0 / Patch=r02.06.00
 * #          : artf189696, artf187980, artf189800
 * #          :
 * #          :
 * # 04.03.01 : PN7462AU_04.03.01_20160706 / EE=r27.0.0 / Patch=r02.06.00
 * #          : NxpNfcRdLib_v4.030.00.011627_20160706
 * #          :
 * # 04.03.00 : PN7462AU_04_03_00_20160704 / EE=r27.0.0 / Patch=r02.06.00
 * #          : NxpNfcRdLib_v4.030.00.001627_20160704
 * #          :
 * # 04.00.00 : PN7462AU_04_00_00 / EE=r27.0.0 / Patch=r02.06.00
 * #          : R Gate FW Release
 * #          :
 * # 03.03.00 : PN7462AU_03_03_00_RC4_1_20160114 / EE=r25.0.0 / Patch=r02.06.00
 * #          : V Gate FW Release
 * #          :
 * # 02.06.02 : PN7462AU_02_06_02_MRA2_20151019 [A2 FW]
 * # _____________________________________________________________________________
 */


#endif /* PN7462AU_VERSION_INFO_H_INCLUDED */
