/*
 *                    Copyright (c), NXP Semiconductors
 *
 *                       (C) NXP Semiconductors 2014,2015
 *
 *         All rights are reserved. Reproduction in whole or in part is
 *        prohibited without the written consent of the copyright owner.
 *    NXP reserves the right to make changes without notice at any time.
 *   NXP makes no warranty, expressed, implied or statutory, including but
 *   not limited to any implied warranty of merchantability or fitness for any
 *  particular purpose, or that the use will not infringe any third party patent,
 *   copyright or trademark. NXP must not be liable for any loss or damage
 *                            arising from its use.
 */

/** @file
 *
 * Run Time configuration settings extracted from EEPROM/FLASH.
 *
 * Project:  PN7462AU
 *
 * $Date: 2016-07-04 23:48:03 +0530 (Mon, 04 Jul 2016) $
 * $Author: Purnank G (ing05193) $
 * $Revision: 18541 $ (v04.11.00)
 */


/* ****************************************************************************************************************** */
/* Generated by user_ee.py version 2016.06.29_00 on 2016-12-09
 */

#include "ph_Datatypes.h"
#include "ph_NxpBuild.h"
#include "phCfg_EE.h"


#if defined(NXPBUILD__CFG_FROM_EE) || defined (NXPBUILD__CFG_ENABLE_EE_DOWNLOAD)

const phCfg_EE_ErrorMem_Err_t * const gpkphCfg_EE_ErrorMem_Err =
    ((phCfg_EE_ErrorMem_Err_t *) PH_CFG_EE_ERR_START_ADDRESS );
const phCfg_EE_Ctrl_VerInfo_t * const gpkphCfg_EE_Ctrl_VerInfo =
    ((phCfg_EE_Ctrl_VerInfo_t *) PH_CFG_EE_VERINFO_START_ADDRESS );
const phCfg_EE_Boot_RNG_t * const gpkphCfg_EE_Boot_RNG =
    ((phCfg_EE_Boot_RNG_t *) PH_CFG_EE_RNG_START_ADDRESS );
const phCfg_EE_Boot_ClkGen_t * const gpkphCfg_EE_Boot_ClkGen =
    ((phCfg_EE_Boot_ClkGen_t *) PH_CFG_EE_CLKGEN_START_ADDRESS );
const phCfg_EE_Boot_PcrPwrTempConfig_t * const gpkphCfg_EE_Boot_PcrPwrTempConfig =
    ((phCfg_EE_Boot_PcrPwrTempConfig_t *) PH_CFG_EE_PCRPWRTEMPCONFIG_START_ADDRESS );
const phCfg_EE_Boot_PcrPwrDown_t * const gpkphCfg_EE_Boot_PcrPwrDown =
    ((phCfg_EE_Boot_PcrPwrDown_t *) PH_CFG_EE_PCRPWRDOWN_START_ADDRESS );
const phCfg_EE_Boot_TxAnaStandByConfig_t * const gpkphCfg_EE_Boot_TxAnaStandByConfig =
    ((phCfg_EE_Boot_TxAnaStandByConfig_t *) PH_CFG_EE_TXANASTANDBYCONFIG_START_ADDRESS );
const phCfg_EE_Boot_EEPROM_t * const gpkphCfg_EE_Boot_EEPROM =
    ((phCfg_EE_Boot_EEPROM_t *) PH_CFG_EE_EEPROM_START_ADDRESS );
const phCfg_EE_Boot_FLASH_t * const gpkphCfg_EE_Boot_FLASH =
    ((phCfg_EE_Boot_FLASH_t *) PH_CFG_EE_FLASH_START_ADDRESS );
const phCfg_EE_Boot_TxLdoParams_t * const gpkphCfg_EE_Boot_TxLdoParams =
    ((phCfg_EE_Boot_TxLdoParams_t *) PH_CFG_EE_TXLDOPARAMS_START_ADDRESS );
const phCfg_EE_Boot_CT_t * const gpkphCfg_EE_Boot_CT =
    ((phCfg_EE_Boot_CT_t *) PH_CFG_EE_CT_START_ADDRESS );
const phCfg_EE_Boot_GPIO_t * const gpkphCfg_EE_Boot_GPIO =
    ((phCfg_EE_Boot_GPIO_t *) PH_CFG_EE_GPIO_START_ADDRESS );
const phCfg_EE_HW_WakeUpConfig_t * const gpkphCfg_EE_HW_WakeUpConfig =
    ((phCfg_EE_HW_WakeUpConfig_t *) PH_CFG_EE_WAKEUPCONFIG_START_ADDRESS );
const phCfg_EE_HW_RfAntennae_t * const gpkphCfg_EE_HW_RfAntennae =
    ((phCfg_EE_HW_RfAntennae_t *) PH_CFG_EE_RFANTENNAE_START_ADDRESS );
const phCfg_EE_HW_RfInitUserEE_t * const gpkphCfg_EE_HW_RfInitUserEE =
    ((phCfg_EE_HW_RfInitUserEE_t *) PH_CFG_EE_RFINITUSEREE_START_ADDRESS );
const phCfg_EE_HW_RfDPC_t * const gpkphCfg_EE_HW_RfDPC =
    ((phCfg_EE_HW_RfDPC_t *) PH_CFG_EE_RFDPC_START_ADDRESS );
const phCfg_EE_HW_RfPcdShaping_t * const gpkphCfg_EE_HW_RfPcdShaping =
    ((phCfg_EE_HW_RfPcdShaping_t *) PH_CFG_EE_RFPCDSHAPING_START_ADDRESS );
const phCfg_EE_HW_RfAPC_t * const gpkphCfg_EE_HW_RfAPC =
    ((phCfg_EE_HW_RfAPC_t *) PH_CFG_EE_RFAPC_START_ADDRESS );
const phCfg_EE_HW_RfInterOpTimings_t * const gpkphCfg_EE_HW_RfInterOpTimings =
    ((phCfg_EE_HW_RfInterOpTimings_t *) PH_CFG_EE_RFINTEROPTIMINGS_START_ADDRESS );
const phCfg_EE_HW_RfHalTimings_t * const gpkphCfg_EE_HW_RfHalTimings =
    ((phCfg_EE_HW_RfHalTimings_t *) PH_CFG_EE_RFHALTIMINGS_START_ADDRESS );
const phCfg_EE_HW_DPLLCfg_t * const gpkphCfg_EE_HW_DPLLCfg =
    ((phCfg_EE_HW_DPLLCfg_t *) PH_CFG_EE_DPLLCFG_START_ADDRESS );
const phCfg_EE_HW_DPLLClkPhaseAdjustment_t * const gpkphCfg_EE_HW_DPLLClkPhaseAdjustment =
    ((phCfg_EE_HW_DPLLClkPhaseAdjustment_t *) PH_CFG_EE_DPLLCLKPHASEADJUSTMENT_START_ADDRESS );
const phCfg_EE_HW_RfLdtParams_t * const gpkphCfg_EE_HW_RfLdtParams =
    ((phCfg_EE_HW_RfLdtParams_t *) PH_CFG_EE_RFLDTPARAMS_START_ADDRESS );
const phCfg_EE_HW_RfTestBus_t * const gpkphCfg_EE_HW_RfTestBus =
    ((phCfg_EE_HW_RfTestBus_t *) PH_CFG_EE_RFTESTBUS_START_ADDRESS );
const phCfg_EE_HW_ClkGenClifClockStart_t * const gpkphCfg_EE_HW_ClkGenClifClockStart =
    ((phCfg_EE_HW_ClkGenClifClockStart_t *) PH_CFG_EE_CLKGENCLIFCLOCKSTART_START_ADDRESS );
const phCfg_EE_HW_I2CM_t * const gpkphCfg_EE_HW_I2CM =
    ((phCfg_EE_HW_I2CM_t *) PH_CFG_EE_I2CM_START_ADDRESS );
const phCfg_EE_HW_SPIM_t * const gpkphCfg_EE_HW_SPIM =
    ((phCfg_EE_HW_SPIM_t *) PH_CFG_EE_SPIM_START_ADDRESS );
const phCfg_EE_HW_HIF_t * const gpkphCfg_EE_HW_HIF =
    ((phCfg_EE_HW_HIF_t *) PH_CFG_EE_HIF_START_ADDRESS );
const phCfg_EE_phRFLP_T_Tx_val_t * const gpkphCfg_EE_phRFLP_T_Tx_val =
    ((phCfg_EE_phRFLP_T_Tx_val_t *) PH_CFG_EE_T_TX_VAL_START_ADDRESS );
const phCfg_EE_phRFLP_T_Rx_val_t * const gpkphCfg_EE_phRFLP_T_Rx_val =
    ((phCfg_EE_phRFLP_T_Rx_val_t *) PH_CFG_EE_T_RX_VAL_START_ADDRESS );
const phCfg_EE_phRFLP_I_Tx_val_t * const gpkphCfg_EE_phRFLP_I_Tx_val =
    ((phCfg_EE_phRFLP_I_Tx_val_t *) PH_CFG_EE_I_TX_VAL_START_ADDRESS );
const phCfg_EE_phRFLP_I_Rx_val_t * const gpkphCfg_EE_phRFLP_I_Rx_val =
    ((phCfg_EE_phRFLP_I_Rx_val_t *) PH_CFG_EE_I_RX_VAL_START_ADDRESS );
const phCfg_EE_Trailer_Last_t * const gpkphCfg_EE_Trailer_Last =
    ((phCfg_EE_Trailer_Last_t *) PH_CFG_EE_LAST_START_ADDRESS );

#endif /* NXPBUILD__CFG_FROM_EE */
