/*******************************************************************************
 *
 *                Copyright (C), NXP Semiconductors
 *
 *                   (C) NXP Semiconductors
 *     All rights are reserved. Reproduction in whole or in part is
 *    prohibited without the written consent of the copyright owner.
 * NXP reserves the right to make changes without notice at any time.
 * NXP makes no warranty, expressed, implied or statutory, including but
 * not limited to any implied warranty of merchantability or fitness for any
 * particular purpose, or that the use will not infringe any third party patent,
 * copyright or trademark. NXP must not be liable for any loss or damage
 *                        arising from its use.
 *
 * *//** \file
 *
 * $Author: Purnank H G (ing05193) $
 * $Revision: 13872 $ (v04.11.00)
 * $Date: 2015-07-16 14:29:05 +0530 (Thu, 16 Jul 2015) $
 *
 *******************************************************************************/
#ifndef PN7462AU_IP_PCR_H_INCLUDED_RORW
#define PN7462AU_IP_PCR_H_INCLUDED_RORW

#define PCR_GPREG0_REG_R (0UL)
#define PCR_GPREG0_REG_W (0UL)
#define PCR_GPREG1_REG_R (0UL)
#define PCR_GPREG1_REG_W (0UL)
#define PCR_GPREG2_REG_R (0UL)
#define PCR_GPREG2_REG_W (0UL)
#define PCR_SYS_REG_R (0UL)
#define PCR_SYS_REG_W (0UL)
#define PCR_PMU_REG_R (0UL)
#define PCR_PMU_REG_W (0UL)
#define PCR_RFLD_REG_R (0UL)
#define PCR_RFLD_REG_W (0UL)
#define PCR_TEMP_REG_R (0UL)
#define PCR_TEMP_REG_W (0UL)
#define PCR_HOSTIF_WAKEUP_CFG_REG_R (0UL)
#define PCR_HOSTIF_WAKEUP_CFG_REG_W (0UL)
#define PCR_WAKEUP_CFG_REG_R (0UL)
#define PCR_WAKEUP_CFG_REG_W (0UL)
#define PCR_GPIO_WAKEUP_CFG_REG_R (0UL)
#define PCR_GPIO_WAKEUP_CFG_REG_W (0UL)
#define PCR_BOOT_REG_R (0UL)
#define PCR_BOOT_REG_W (0UL)
#define PCR_CTRL_REG_R (0UL)
#define PCR_CTRL_REG_WO (0UL) /* Allow single bit access */
#define PCR_CTRL_REG_W (0UL)
#define PCR_CLK_CFG_REG_R (0UL)
#define PCR_CLK_CFG_REG_W (0UL)
#define PCR_CLK_CFG2_REG_R (0UL)
#define PCR_CLK_CFG2_REG_W (0UL)
#define PCR_PADIN_REG_R (0UL)
#define PCR_PADOUT_REG_R (0UL)
#define PCR_PADOUT_REG_W (0UL)
#define PCR_PAD_ATX_A_REG_R (0UL)
#define PCR_PAD_ATX_A_REG_W (0UL)
#define PCR_PAD_ATX_B_REG_R (0UL)
#define PCR_PAD_ATX_B_REG_W (0UL)
#define PCR_PAD_ATX_C_REG_R (0UL)
#define PCR_PAD_ATX_C_REG_W (0UL)
#define PCR_PAD_ATX_D_REG_R (0UL)
#define PCR_PAD_ATX_D_REG_W (0UL)
#define PCR_PADDWL_REQ_REG_R (0UL)
#define PCR_PADDWL_REQ_REG_W (0UL)
#define PCR_PAD_INT_AUX_REG_R (0UL)
#define PCR_PAD_INT_AUX_REG_W (0UL)
#define PCR_PAD_IO_AUX_REG_R (0UL)
#define PCR_PAD_IO_AUX_REG_W (0UL)
#define PCR_PAD_CLK_AUX_REG_R (0UL)
#define PCR_PAD_CLK_AUX_REG_W (0UL)
#define PCR_PADIRQ_REG_R (0UL)
#define PCR_PADIRQ_REG_W (0UL)
#define PCR_PADGPIO1_REG_R (0UL)
#define PCR_PADGPIO1_REG_W (0UL)
#define PCR_PADGPIO2_REG_R (0UL)
#define PCR_PADGPIO2_REG_W (0UL)
#define PCR_PADGPIO3_REG_R (0UL)
#define PCR_PADGPIO3_REG_W (0UL)
#define PCR_PADGPIO4_REG_R (0UL)
#define PCR_PADGPIO4_REG_W (0UL)
#define PCR_PADGPIO5_REG_R (0UL)
#define PCR_PADGPIO5_REG_W (0UL)
#define PCR_PADGPIO6_REG_R (0UL)
#define PCR_PADGPIO6_REG_W (0UL)
#define PCR_PADGPIO7_REG_R (0UL)
#define PCR_PADGPIO7_REG_W (0UL)
#define PCR_PADGPIO8_REG_R (0UL)
#define PCR_PADGPIO8_REG_W (0UL)
#define PCR_PADGPIO9_REG_R (0UL)
#define PCR_PADGPIO9_REG_W (0UL)
#define PCR_PADGPIO10_REG_R (0UL)
#define PCR_PADGPIO10_REG_W (0UL)
#define PCR_PADGPIO11_REG_R (0UL)
#define PCR_PADGPIO11_REG_W (0UL)
#define PCR_PADGPIO12_REG_R (0UL)
#define PCR_PADGPIO12_REG_W (0UL)
#define PCR_PADSWDIO_REG_R (0UL)
#define PCR_PADSWDIO_REG_W (0UL)
#define PCR_PADSWDCLK_REG_R (0UL)
#define PCR_PADSWDCLK_REG_W (0UL)
#define PCR_PADSWP_REG_R (0UL)
#define PCR_PADSWP_REG_W (0UL)
#define PCR_PAD_SWPM_DWP_REG_R (0UL)
#define PCR_PAD_SWPM_DWP_REG_W (0UL)
#define PCR_PADIICM_REG_R (0UL)
#define PCR_PADIICM_REG_W (0UL)
#define PCR_ANA_TX_STANDBY_REG_R (0UL)
#define PCR_ANA_TX_STANDBY_REG_W (0UL)
#define PCR_ANA_TXPROT_REG_R (0UL)
#define PCR_ANA_TXPROT_REG_W (0UL)
#define PCR_TBSEL_REG_R (0UL)
#define PCR_TBSEL_REG_W (0UL)
#define PCR_SPIM_REG_R (0UL)
#define PCR_SPIM_REG_W (0UL)
#define PCR_CTIF_REG_R (0UL)
#define PCR_CTIF_REG_W (0UL)
#define PCR_HOSTIF_SAVE1_REG_R (0UL)
#define PCR_HOSTIF_SAVE1_REG_W (0UL)
#define PCR_HOSTIF_SAVE2_REG_R (0UL)
#define PCR_HOSTIF_SAVE2_REG_W (0UL)
#define PCR_TXLDO_MON_REG_R (0UL)
#define PCR_TXLDO_MON_REG_W (0UL)
#define PCR_BOOT2_REG_R (0UL)
#define PCR_BOOT2_REG_W (0UL)
#define PCR_GPREG3_REG_R (0UL)
#define PCR_GPREG3_REG_W (0UL)
#define PCR_GPREG4_REG_R (0UL)
#define PCR_GPREG4_REG_W (0UL)
#define PCR_GPREG5_REG_R (0UL)
#define PCR_GPREG5_REG_W (0UL)
#define PCR_GPREG6_REG_R (0UL)
#define PCR_GPREG6_REG_W (0UL)
#define PCR_GPREG7_REG_R (0UL)
#define PCR_GPREG7_REG_W (0UL)
#define PCR_GPIO_INT_ACTIVE_LOW_REG_R (0UL)
#define PCR_GPIO_INT_ACTIVE_LOW_REG_W (0UL)
#define PCR_GPIO_INT_LEVEL_SENSE_REG_R (0UL)
#define PCR_GPIO_INT_LEVEL_SENSE_REG_W (0UL)
#define PCR_GPIO_INT_ACTIVE_BOH_EDGE_REG_R (0UL)
#define PCR_GPIO_INT_ACTIVE_BOH_EDGE_REG_W (0UL)
#define PCR_SELECT_SYSTEMCLOCK_R (0UL)
#define PCR_SELECT_SYSTEMCLOCK_W (0UL)
#define PCR_ADV_RFLD_REG_R (0UL)
#define PCR_ADV_RFLD_REG_W (0UL)
#define PCR_ADV_RFLD_TEST_REG_R (0UL)
#define PCR_ADV_RFLD_TEST_REG_W (0UL)
#define PCR_INT_CLR_ENABLE_REG_WO (0UL)
#define PCR_INT_CLR_ENABLE_REG_W (0UL)
#define PCR_INT_SET_ENABLE_REG_WO (0UL)
#define PCR_INT_SET_ENABLE_REG_W (0UL)
#define PCR_INT_STATUS_REG_R (0UL)
#define PCR_INT_ENABLE_REG_R (0UL)
#define PCR_INT_CLR_STATUS_REG_WO (0UL)
#define PCR_INT_CLR_STATUS_REG_W (0UL)
#define PCR_INT_SET_STATUS_REG_WO (0UL)
#define PCR_INT_SET_STATUS_REG_W (0UL)

#endif /* PN7462AU_IP_PCR_H_INCLUDED_RORW */
