#ifndef PN7462AU_IP_REGCORE_H_INCLUDED_RORW
#define PN7462AU_IP_REGCORE_H_INCLUDED_RORW



/* Values from PN7462AU_REGISTERSCORE */
#define SYST_CSR_REG_R (0UL)
#define SYST_CSR_REG_W (0UL)
#define SYST_RVR_REG_R (0UL)
#define SYST_RVR_REG_W (0UL)
#define SYST_CVR_REG_R (0UL)
#define SYST_CVR_REG_W (0UL)
#define SYST_CVR_REG_VALUE_MASK_R (0UL)
#define SYST_CALIB_REG_R (0UL)
#define NVIC_ISER_REG_R (0UL)
#define NVIC_ISER_REG_W (0UL)
#define NVIC_ICER_REG_R (0UL)
#define NVIC_ICER_REG_W (0UL)
#define NVIC_ISPR_REG_R (0UL)
#define NVIC_ISPR_REG_W (0UL)
#define NVIC_ICPR_REG_R (0UL)
#define NVIC_ICPR_REG_W (0UL)
#define NVIC_IPR0_REG_R (0UL)
#define NVIC_IPR0_REG_W (0UL)
#define NVIC_IPR1_REG_R (0UL)
#define NVIC_IPR1_REG_W (0UL)
#define NVIC_IPR2_REG_R (0UL)
#define NVIC_IPR2_REG_W (0UL)
#define NVIC_IPR3_REG_R (0UL)
#define NVIC_IPR3_REG_W (0UL)
#define NVIC_IPR4_REG_R (0UL)
#define NVIC_IPR4_REG_W (0UL)
#define NVIC_IPR5_REG_R (0UL)
#define NVIC_IPR5_REG_W (0UL)
#define NVIC_IPR6_REG_R (0UL)
#define NVIC_IPR6_REG_W (0UL)
#define NVIC_IPR7_REG_R (0UL)
#define NVIC_IPR7_REG_W (0UL)
#define SVC_SHPR2_REG_R (0UL)
#define SVC_SHPR2_REG_W (0UL)


#endif /* PN7462AU_IP_REGCORE_H_INCLUDED_RORW */
